### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by wy15** [oslabs-beta/vno#73]
```bash
  ~ ❯ deno -V                                                                                                         14:45:53
deno 1.7.0
  ~ ❯ deno install --allow-net --unstable https://deno.land/x/vno/install/vno.ts                                      14:45:56
Check https://deno.land/x/vno/install/vno.ts
error: TS2339 [ERROR]: Property 'compile' does not exist on type 'typeof Deno'.
    const [, outPut] = await Deno.compile(
                                  ~~~~~~~
    at https://deno.land/x/vno@v1.0.4/lib/utils.ts:112:35

TS2571 [ERROR]: Object is of type 'unknown'.
      !chunk.includes("file:///")
       ~~~~~
    at https://deno.land/x/vno@v1.0.4/lib/utils.ts:120:8

TS2571 [ERROR]: Object is of type 'unknown'.
    return cut ? script.substring(3, script.length - 4) : script;
                 ~~~~~~
    at https://deno.land/x/vno@v1.0.4/lib/utils.ts:125:18

TS2571 [ERROR]: Object is of type 'unknown'.
    return cut ? script.substring(3, script.length - 4) : script;
                                     ~~~~~~
    at https://deno.land/x/vno@v1.0.4/lib/utils.ts:125:38

TS2339 [ERROR]: Property 'bundle' does not exist on type 'typeof Deno'.
      const [diagnostic, output] = await Deno.bundle(
                                              ~~~~~~
    at https://deno.land/x/vno@v1.0.4/lib/utils.ts:151:47

TS7006 [ERROR]: Parameter 'file' implicitly has an 'any' type.
        diagnostic.forEach((file) => {
                            ~~~~
    at https://deno.land/x/vno@v1.0.4/lib/utils.ts:159:29

Found 6 errors.
```

**Comment by buttercubz** [comment]
see https://github.com/oslabs-beta/vno/issues/57#issuecomment-760243139 I'm already working to fix it so I think I'll have it soon, I could continue using it in the previous version

**Comment by wy15** [comment]
Thanks for what you did。
